```{r}
uu<-seq(0,1,length=100)
uu<-uu[c(-1,-100)]
z_score<-qnorm(uu) 
pvalues<-pnorm(z_score) 
plot(z_score,pvalues,type="l",
     xlab= "z-scores",
     ylab="probability",
     xaxt="n",
     main="CDF")
      
axis(1, at=which(round(pvalues,2) == 0.2),labels=round(qnorm(0.2), 2))



```

```{r}
uu<-seq(0,1,length=10)


z_scores <- qnorm(uu) 
z_scores[3]<-NA 

which(z_scores==Inf) 
which(z_scores==-Inf) 

which(z_scores==NA) 
NA==NA 
NA==0 
NA==Inf 
NA=="dd" 
is.na(z_scores) 
cl<-z_scores [which(!is.na(z_scores))] 

c2<-z_scores[!is.na(z_scores)]



```

```{r}
right<-pnorm(2)
left<-pnorm(-2)
right-left 

```

```{r}
percentbysd<-function (sd){
right<-pnorm(sd)
left<-pnorm(-sd)
return(right-left)
}
percentbysd(1)

```
我要寫一個函數
用來過濾-2到+2之間的值
```{r}
myfilter<-function(x) {
   le2<- x[x<=0.2] 
   xx<-le2[le2>=-0.2] 
   return(xx)
   } 
x<-rnorm(10) 
myfilter(x)

```
給我一個向量
x<-rpois(30,2)
寫一個函數要找出來偶數

```{r}
x<-rpois(30,2)

getevent<-function(v){
  return(v[v%%2==0])
}
x
getevent(x)

```








